"""
HTML Report Generator

Generates an HTML report for VulnProbe scan results.
"""

from datetime import datetime
import webbrowser
import os

def generate_html_report(target, results):
    """
    Generates an HTML report for the scan results.
    """

    # Create reports directory if it doesn't exist
    os.makedirs("reports", exist_ok=True)

    # Generate timestamped filename
    timestamp = datetime.now().strftime("%Y-%m-%d_%H-%M-%S")
    filename = f"reports/scan_report_{timestamp}.html"

    # HTML Header
    html = f"""
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="UTF-8">

    <title>VulnProbe Scan Report</title>

    <style>

        body {{
            font-family: Arial, Helvetica, sans-serif;
            background-color: #f4f4f4;
            margin: 40px;
            color: #333;
        }}

        h1 {{
            text-align: center;
            color: #222;
        }}

        .summary {{
            background: white;
            padding: 20px;
            border-radius: 8px;
            margin-bottom: 30px;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
        }}

        table {{
            width: 100%;
            border-collapse: collapse;
            background: white;
            box-shadow: 0 2px 8px rgba(0,0,0,0.1);
        }}

        th {{
            background: #222;
            color: white;
            padding: 12px;
        }}

        td {{
            padding: 12px;
            border-bottom: 1px solid #ddd;
            text-align: center;
        }}

        tr:nth-child(even) {{
            background: #f9f9f9;
        }}

        tr:hover {{
            background: #f1f1f1;
        }}

        .safe {{
            color: green;
            font-weight: bold;
        }}

        .low {{
            color: #1e90ff;
            font-weight: bold;
        }}

        .medium {{
            color: orange;
            font-weight: bold;
        }}

        .high {{
            color: darkorange;
            font-weight: bold;
        }}

        .critical {{
            color: red;
            font-weight: bold;
        }}

        footer {{
            margin-top: 30px;
            text-align: center;
            color: gray;
            font-size: 14px;
        }}

    </style>

</head>

<body>

<h1>VulnProbe Scan Report</h1>

<div class="summary">

    <p><strong>Target:</strong> {target}</p>

    <p><strong>Scan Date:</strong> {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}</p>

    <p><strong>Open Ports Found:</strong> {len(results)}</p>

</div>

<table>

<tr>
    <th>Port</th>
    <th>Service</th>
    <th>Banner</th>
    <th>Risk</th>
</tr>
"""

    # Generate table rows
    for result in results:

        risk = "Safe"
        css = "safe"

        if result["vulnerability"]:

            risk = result["vulnerability"]["risk"]

            risk_lower = risk.lower()

            if risk_lower == "low":
                css = "low"

            elif risk_lower == "medium":
                css = "medium"

            elif risk_lower == "high":
                css = "high"

            elif risk_lower == "critical":
                css = "critical"

        html += f"""
<tr>

    <td>{result['port']}</td>

    <td>{result['service']}</td>

    <td>{result['banner']}</td>

    <td class="{css}">{risk}</td>

</tr>
"""

    # Close HTML
    html += """
</table>

<footer>

    <p>Generated by VulnProbe</p>

</footer>

</body>

</html>
"""

    # Save report
    with open(filename, "w", encoding="utf-8") as report:
        report.write(html)
    webbrowser.open(f"file://{os.path.abspath(filename)}")
    return filename